Chat.FrontWeb/Controllers/TradingController.cs
using SDMS.DTO.DTO;
using Chat.FrontWeb.Controllers.Base;
using Chat.FrontWeb.Models.Stock;
using Chat.IService.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Chat.FrontWeb.Controllers
{
    public class TradingController : FrontBaseController
    {
        public IStockService stockService { get; set; }
        public IUserService UserServer { set; get; }
        
        // GET: Trading
        public ActionResult TradingHall()
        {
            StockView model = new StockView();
            string number = Request.Params["number"];
            string price = Request.Params["price"];
            if (number != null && price != null)
            {
                if(number!="" && price != "")
                {
                    model.StockViewList = stockService.GetStockList(pageIndex, pageSize).Where(r => r.Number == int.Parse(number)).Where(r => r.Price == decimal.Parse(price)).ToList();
                    model.totalPage = stockService.GetStockCount().Where(r => r.Number == int.Parse(number)).Where(r => r.Price == decimal.Parse(price)).ToList().Count;
                }
                else if(number != "" && price == "")
                {
                    model.StockViewList = stockService.GetStockList(pageIndex, pageSize).Where(r => r.Number == int.Parse(number)).ToList();
                    model.totalPage = stockService.GetStockCount().Where(r => r.Number == int.Parse(number)).ToList().Count;
                }
                else if (number == "" && price != "")
                {
                    model.StockViewList = stockService.GetStockList(pageIndex, pageSize).Where(r => r.Price == decimal.Parse(price)).ToList();
                    model.totalPage = stockService.GetStockCount().Where(r => r.Price == decimal.Parse(price)).ToList().Count;
                }
            
            }else if(number== null && price == null)
            {
                model.StockViewList = stockService.GetStockList(pageIndex, pageSize);
                model.totalPage = stockService.GetStockCount().Count;
            }
            for (int i = 0; i < model.StockViewList.Count; i++)
            {
                UserDTO usermodel = UserServer.GetModel(model.StockViewList[i].UserID);
                if (model != null)
                {

                    model.StockViewList[i].UserCode = usermodel.UserCode;
                }
            }
           // model.totalPage = stockService.GetStockCount().Count;
            decimal s = (decimal)model.totalPage / (decimal)pageSize;
            model.showPageNum = int.Parse(Math.Ceiling(s).ToString());
            return View(model);
        }
        public ActionResult Sell()
        {
            ViewBag.UserCode = UserServer.GetModel(9).UserCode;
            ViewBag.Emoney = UserServer.GetModel(9).Emoney;
            return View();
        }
        [HttpPost]
        public ActionResult TradingModel(StockDTO model)
        {
            string msg = "";
            if (model.Number == 0)
            {
                msg = "卖出数量不能为空";
            }
            if (model.Price == 0)
            {
                msg = "卖出价格不能为空";
            }
            UserDTO us = UserServer.GetModel(model.UserCode);
            if (us.Emoney >= model.Number)
            {
                model.StockID = 1;
                model.UserID = Convert.ToInt32(us.ID);
                model.IsDeleted = false;
                model.CreateTime = DateTime.Now;
                model.BuyDate = DateTime.Now;
                model.Surplus = model.Number;
                long Id = stockService.Add(model);
                us.Emoney = us.Emoney - model.Number;
                if (Id > 0 && UserServer.UpdateEmoney(us))
                {
                    msg = "卖出成功";
                }
                else
                {
                    msg = "卖出失败";
                }
            }
            else
            {
                msg = "余额不足";
            }
            
            return Content("<script>alert('" + msg + "');window.location='/Trading/TradingHall';</script>");
        }
    }
}

Chat.FrontWeb/Views/Trading/Sell.cshtml
@model Chat.DTO.DTO.StockDTO
@{
    ViewBag.Title = "Sell";
    Layout = "~/Views/Share/_Layout2.cshtml";
}

@using (Html.BeginForm("TradingModel", "Trading", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="wrapper">
        <section class="panel">
            <!--主体开始-->
            <section style="padding: 28px;">
                <div class="row">
                    <div class="col-md-12">
                        <div class="widget panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">基本信息</h3>
                            </div>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="widget widget-body-white padding-none">
                                <div class="widget-body" style="padding: 20px; overflow: auto;">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="widget-body" style="padding: 20px; overflow: auto;">
                                        <div class="row">
                                            <div class="form-group" style="padding: 10px;">
                                                <label class="col-md-3 control-label">会员编号:</label>
                                                <div class="col-md-6">
                                                    <input type="text" name="UserCode" value="@ViewBag.UserCode" class="form-control" readonly="readonly" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row" style="padding: 10px;">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">币种数量:</label>
                                                <div class="col-md-6">
                                                    <input type="text" name="Emoney" value="@ViewBag.Emoney" class="form-control" readonly="readonly" />

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="widget panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">出售信息</h3>
                            </div>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="widget widget-body-white padding-none">
                                <div class="widget-body" style="padding: 20px; overflow: auto;">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    <div class="widget-body" style="padding: 20px; overflow: auto;">
                                        <div class="row" style="display:none">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label"></label>
                                                <div class="col-md-6">
                                                    @Html.HiddenFor(model => model.UserID, new { htmlAttributes = new { @class = "form-control" } })
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row" style="padding: 10px;">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">卖出数量<span class="ast">*</span>:</label>
                                                <div class="col-md-6">
                                                    @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row" style="padding: 10px;">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">卖出价格(个/币)<span class="ast">*</span>:</label>
                                                <div class="col-md-6">
                                                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row" style="padding: 10px;">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label"></label>
                                                <div class="col-md-6">
                                                    <input type="submit" value="提交" class="btn btn-default" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </section>
    </div>
}
<script>
    $(function () {
        $('form').bind('submit', checkform);
    })
    function checkform() {
        if ($("#Number").val() == "") {
            alert("卖出数量不能为空");
            return false;
        }
        if ($("#Price").val() == "") {
            alert("卖出价格不能为空");
            return false;
        }
    }
</script>

Chat.FrontWeb/Views/Trading/TradingHall.cshtml
@model Chat.FrontWeb.Models.Stock.StockView

@{
    ViewBag.Title = "TradingHall";
    Layout = "~/Views/Share/_Layout2.cshtml";
}

<section class="wrapper">
    <section class="panel">
        <!--主体开始-->
        <section style="padding: 28px;">
            <div id='myform'>
                <div class="row">
                    <div class="col-md-12">
                        <div class="widget panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    交易大厅
                                </h3>
                            </div>
                            <div class="widget widget-body-white padding-none">
                                <div class="widget-body" style="padding: 20px; overflow: auto;">
                                    <div class="row" style="padding: 10px;">
                                        <div class="form-group">
                                            <label>挂卖价格</label><input type="text" id="price" />
                                            <label>挂卖数量</label><input type="text" id="number" />
                                            <input id="btn" type="button" value="搜索" class="btn btn-primary" required />
                                            <input id="btnsell" type="button" value="我要卖出" class="btn btn-primary" required />
                                        </div>
                                    </div>
                                    <div class="widget-body innerAll overthrow col-md-12" style="padding: 20px; overflow: auto;">
                                        <table class="table table-bordered table-primary tab">
                                            <thead>
                                                <tr class="tac">
                                                    <th>会员编号</th>
                                                    <th>挂卖数量</th>
                                                    <th>挂卖价格</th>
                                                    <th>发布时间</th>
                                                    <th>操作</th>
                                                </tr>
                                            </thead>
                                            <tbody id="pagerList">
                                                @foreach (var item in Model.StockViewList)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.UserCode)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Number)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Price)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.BuyDate)
                                                        </td>
                                                        <td>
                                                           <a href="#">购买</a>
                                                        </td>
                                                    </tr>
                                                    <tr id="trNull" hidden="hidden">
                                                        <td colspan="4" align="center"><div class="NoData"><span class="cBlack"> <img src="/Areas/Admin/Content/Images/ico_NoDate.gif" width="16" height="16" /> 抱歉！目前数据库暂无数据。</span></div></td>
                                                    </tr>
                                                }
                                        </table>
                                        <div class="nextpage">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</section>
<script>
    $(".nextpage").PageGrivView({
        totalPage:@Model.showPageNum,
        showPageNum:@Model.totalPage,
        url: "/Trading/TradingHall",
        obj: ".tab",
        css: "css-1"/**css-1到css-5**/

    });
    $(function () {
        $("#btn").click(function () {
            var number = $("#number").val();
            var price = $("#price").val();
            $.ajax({
                type: 'POST',
                url: "/Trading/TradingHall",
                data: { number: number, price: price },
               
                success: function (data) {
                    $(".tab").replaceWith($(data).find(".tab"));
                    //alert(data);
                    console.log("请求成功");
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {//请求失败处理函数
                    console.log("请求失败");
                }
            });
        })
        $("#btnsell").click(function () {
            window.location.href = "/Trading/Sell";
        })
        $("a").click(function () {
            window.location.href = "/Trading/Sell";
        })
    })
        //function onchUser() {
        //    var code = $("#usercode").val();
        //    if (code != "") {
        //        $.ajax({
        //            type: 'POST',
        //            url: "/Admin/Team/GetUseLevelName?code=" + code,
        //            dataType: 'text',
        //            async: false,
        //            success: function (responseData) {
        //                if (responseData == "会员不存在") {
        //                    $("#usercode").val("");
        //                    alert(responseData);
        //                } else { $("#txtLevel").val(responseData); }
        //            },
        //            error: function (XMLHttpRequest, textStatus, errorThrown) {//请求失败处理函数
        //                console.log("请求失败");
        //            }
        //        });
        //    }
        //}
        //function onSubmit() {
        //    var code = $("#usercode").val();
        //    var levelID = $("#levelName").val();
        //    if (code != "") {
        //        $.ajax({
        //            type: 'POST',
        //            url: "/Admin/Team/ProUserLevel?code=" + code + "&leveID=" + levelID,
        //            dataType: 'json',
        //            async: false,
        //            success: function (responseData) {
        //                if (responseData.Status == 1) {
        //                    //$("#usercode").val("");
        //                    location.reload();
        //                    alert(responseData.msg);
        //                    // window.location.reload();
        //                } else {
        //                    alert(responseData.msg);
        //                }
        //            },
        //            error: function (XMLHttpRequest, textStatus, errorThrown) {//请求失败处理函数
        //                console.log("请求失败");
        //            }
        //        });
        //    } else {
        //        alert("请输入要升级的会员");
        //    }
        //}
</script>