Chat.FrontWeb/Areas/Admin/Models/Team/UserProView.cs
using SDMS.DTO.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chat.FrontWeb.Areas.Admin.Models.Team
{
    public class UserProView
    {
        public List<UserProDTO> UserProViewList { set; get; }
        public int totalPage { set; get; }
        public int showPageNum { set; get; }
    }
}

Chat.FrontWeb/Models/Team/TreeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Chat.FrontWeb.Models.Team
{
    public class TreeViewModel
    {
        public string Tree { get; set; }
        public long Id { get; set; }
    }
}

Chat.FrontWeb/Areas/Admin/Controllers/TeamController.cs
using SDMS.DTO.DTO;
using Chat.FrontWeb.Areas.Admin.Controllers.Base;
using Chat.FrontWeb.Areas.Admin.Models.Team;
using Chat.FrontWeb.Common;
using Chat.IService.Interface;
using Chat.Service.Entities;
using Chat.WebCommon;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Chat.FrontWeb.Areas.Admin.Controllers
{
    public class TeamController : AdminBaseController
    {
        public ILevelService lvelname { get; set; } 
        public IUserService UserServer { set; get; }
        public IMemberLevelService MemberLevelService { get; set; }
        public IMemberService Member { get; set; }
        public IGlobeParamService GlobeParamService { get; set; }
        // GET: Admin/Team
        /// <summary>
        /// 系谱图
        /// </summary>
        /// <returns></returns>
        public ActionResult MemberTree()
        {             
            return View();
        }
        public ActionResult Register()
        {
            ViewBag.LeveModelList= lvelname.GetAll();
           
            return View();
        }
        public string RegMoney()
        {
            if (Request.Params["id"] == "1")
            {
                return "100";
            }
            else if (Request.Params["id"] == "2")
            {
                return "200";
            }
            else
            {
                return "0";
            }
        }
        [HttpPost]
        public ActionResult RegisterModel(UserDTO model)
        {
            string msg = "";
            Validate(model);
            if (ModelState.IsValid)
            {
                UserDTO userParanmodel = UserServer.GetModelCode(model.ParentCode);//查询父级信息
                UserDTO userRecommendnmodel = UserServer.GetModelCode(model.RecommendCode);//查询推荐人信息
                if (userParanmodel != null && userRecommendnmodel != null)
                {
                    model.ParentID = int.Parse(userParanmodel.ID.ToString());
                    model.Layer = userParanmodel.Layer + 1;
                    model.AgentsID = 0;
                    model.Emoney = 0;
                    model.BonusAccount = 0;
                    model.AllBonusAccount = 0;
                    model.StockAccount = 0;
                    model.StockMoney = 0;
                    model.User003 = 0;
                    model.ShopAccount = 0;
                    model.LeftScore = 0;
                    model.LeftNewScore = 0;
                    model.LeftBalance = 0;
                    model.CenterScore = 0;
                    model.CenterNewScore = 0;
                    model.CenterBalance = 0;
                    model.RightScore = 0;
                    model.RightNewScore = 0;
                    model.RightBalance = 0;
                    model.IsOpend = 0;
                    model.IsLock = 0;
                    model.IsAgent = 0;
                    model.BillCount = 0;
                    model.RecommendGenera = userRecommendnmodel.RecommendGenera + 1;
                    model.RecommendID = int.Parse(userRecommendnmodel.ID.ToString());
                    model.RegMoney = 0;
                    model.RegTime = DateTime.Now;
                    model.CreateTime = DateTime.Now;
                    model.Password = CommonHelper.GetMD5(model.Password);
                    long Id = UserServer.Add(model);
                    if (Id > 0)
                    {
                        model.ID = Id;
                        model.UserPath = userParanmodel.UserPath + "-" + Id;
                        model.RecommendPath = userRecommendnmodel.RecommendPath + "-" + Id;
                        UserServer.UpdatePath(model);
                        msg= "注册成功";
                    }
                    else
                    {
                        msg = "注册失败";
                    }
                }
                else
                {
                    msg = "推荐人不存在或安置会员不存在";
                }
            }
            else
            {
                string error = string.Empty;
                foreach (var key in ModelState.Keys)
                {
                    var state = ModelState[key];
                    if (state.Errors.Any())
                    {
                        error = state.Errors.First().ErrorMessage;
                        break;
                    }
                }
                msg = error;
            }
            
            return Content("<script>alert('"+ msg + "');window.location='/Admin/Team/Register';</script>");
        }
        private void Validate(UserDTO model)
        {
            if (string.IsNullOrEmpty(model.UserCode))
            {
                ModelState.AddModelError("UserCode", "用户编号不能为空");
                return;
            }
            if (string.IsNullOrEmpty(model.Password))
            {
                ModelState.AddModelError("Password", "密码不能为空");
                return;
            }
            if (string.IsNullOrEmpty(model.LevelID.ToString()))
            {
                ModelState.AddModelError("LevelID", "等级不能为空");
                return;
            }
            if (string.IsNullOrEmpty(model.RegMoney.ToString()))
            {
                ModelState.AddModelError("RegMoney", "注册金额不能为空");
                return;
            }
            if (string.IsNullOrEmpty(model.RecommendCode))
            {
                ModelState.AddModelError("RecommendCode", "推荐人不能为空");
                return;
            }
            if (string.IsNullOrEmpty(model.ParentCode))
            {
                ModelState.AddModelError("ParentCode", "安置会员不能为空");
                return;
            }
            if (string.IsNullOrEmpty(model.Location.ToString()))
            {
                ModelState.AddModelError("Location", "安置区域不能为空");
                return;
            }
            if (string.IsNullOrEmpty(model.TrueName))
            {
                ModelState.AddModelError("TrueName", "会员姓名不能为空");
                return;
            }
            if (string.IsNullOrEmpty(model.PhoneNum))
            {
                ModelState.AddModelError("PhoneNum", "手机号码不能为空");
                return;
            }
        }
        public string Tree()
        {
            UserView uv = new UserView();
            long Id = Convert.ToInt32(Request.Params["Id"]);
            string code = Request.Params["code"];
            int znode = Convert.ToInt32(Request.Params["znode"]);
            UserDTO model = UserServer.GetModelCode(code);
            if (model != null)
            {
                if (Id == 0)
                {
                    Id = model.ID;
                }

            }
            return uv.AddTable(Id, znode);
        }
        public ActionResult RecommendTree()
        {
            return View();
        }
        #region 加载tree节点
        /// <summary>
        /// 加载tree节点
        /// </summary>
        /// <param name="context"></param>
        /// <param name="uid"></param>
        /// <returns></returns>
        public string TreeMethod(int uid, string id)
        {

            StringBuilder sb = new StringBuilder();
            //int uid = Convert.ToInt32(Request.QueryString["uid"]);
            if (id != "#")
            {
                uid = int.Parse(id);
            }
            UserDTO us = UserServer.GetModel(uid);

            //string treeTxte = "";0

            //if (root)
            //{
            IList<UserDTO> list = UserServer.GetRecommendModelList(us.ID);
            string treeTxte = Treetext(uid);
            if (id == "#")
            {
                sb.Append("\"text\":\"" + treeTxte + "\",\"expanded\":\"false\",\"state\":{\"opened\":\"true\"}");
            }
            if (list.Count > 0)
            {
                if (id == "#")
                {
                    sb.Append(",\"children\":[{");
                }

                for (int i = 0; i < list.Count; i++)
                {
                    // sb.Append(TreeMethod(Convert.ToInt32(list[i].ID)));

                    IList<UserDTO> list2 = UserServer.GetRecommendModelList(list[i].ID);
                    if (list2.Count > 0)
                    {
                        sb.Append("\"text\":\"" + Treetext(Convert.ToInt32(list[i].ID)) + "\",\"children\":true,\"id\":\"" + list[i].ID + "\"");
                    }
                    else
                    {
                        sb.Append("\"text\":\"" + Treetext(Convert.ToInt32(list[i].ID)) + "\"");
                    }

                    if (i != list.Count - 1)
                    {
                        sb.AppendLine("},{");
                    }
                }
                if (id == "#")
                {
                    sb.Append("}]");
                }
            }
            return "[{" + sb.ToString() + "}]";
        }
        public string Treetext(int uid)
        {
            string treeTxte = "";
            UserDTO Model = new UserDTO();
            //AllCore allcore = new AllCore();
            if (UserServer.GetModel(uid) == null)
            {
                return null;
            }
            Model = UserServer.GetModel(uid);
            string LevelName = "";
            if (Model.LevelID == 0)
            {
                LevelName = "无等级";
            }
            else
            {
                LevelName = lvelname.GetLevelName(Model.LevelID).LevelName;
            }

            string dd = "";
            // decimal allEmoney = 0;
            // allEmoney =userBLL.GetEmeony(uid);
            if (Model.IsOpend == 0)
            {
                dd = "[<span style='color:red;'>未开通</span>]";
            }
            else if (Model.IsOpend == 2)
            {
                dd = "已开通";
            }
            if (uid == 2)
            {
                return null;
            }
            else
            {
                string enlevel = "", saleLevel = "";

Chat.FrontWeb/Views/Team/MemberTree.cshtml
@model Chat.FrontWeb.Models.Team.TreeViewModel
@{
    ViewBag.Title = "MemberTree";
    Layout = "~/Views/Share/_Layout2.cshtml";
}

<h2>系谱图</h2>
<div>
    <h2>
        
    </h2>
    <input type="hidden" id="id" value="@Model.Id" />
    <div class="filter">
        <div class="row-fluid">
            会员编号:<input id="txtUserCode" tip="输入会员编号"  type="text" />&nbsp;&nbsp;
            <input type="button" id="btnSearch" value="跳 转" class="btn btn-primary" onclick="onserch()" />&nbsp;&nbsp;
            <input type="button" id="btnMy" value="我的系谱图" class="btn btn-primary" onclick="Myonserch()" />&nbsp;&nbsp;
            <input type="button" id="Button1" value="上一级" class="btn btn-primary" onclick="Uponserch()" />&nbsp;&nbsp;
            <input type="button" id="Button2" value="下一级" class="btn btn-primary" onclick="Downonserch()" />&nbsp;&nbsp;
        </div>
    </div>
    <div class="operation">
        <div style="width: 74px; height: 20px; float: left; color: #fff; background: url('/images/000.jpg'); text-align: center; line-height: 20px; font-weight: bold;">未开通</div>
        <div style="width: 74px; height: 20px; float: left; color: #fff; background: url('/images/001.jpg'); text-align: center; line-height: 20px; font-weight: bold;">银卡代理<!--银卡代理--></div>
        <div style="width: 74px; height: 20px; float: left; color: #fff; background: url('/images/002.jpg'); text-align: center; line-height: 20px; font-weight: bold;">金卡代理<!--金卡代理--></div>
        <div style="width: 74px; height: 20px; float: left; color: #fff; background: url('/images/003.jpg'); text-align: center; line-height: 20px; font-weight: bold;">钻卡代理<!--钻卡代理--></div>
    </div>
    <div class="dataTable" style="clear: both; text-align: center; overflow: auto; margin-left: auto; margin-right: auto; float: inherit;">
        <table style="width: 100%;" cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    @Html.Raw(Model.Tree)
                </td>
            </tr>
        </table>
    </div>
</div>
<script>
    var z = 3;
    var id = $("#id").val();
    //$(function () {
    //    BindTree(22, '45522', z);
    //})
    function BindTree(Id, code, z) {
        $.ajax({
            type: 'POST',
            url: "/Team/Tree?Id=" + Id + "&code=" + code + "&znode=" + z,
            dataType: 'text',
            async: false,
            success: function (responseData) {
                $(".dataTable").html(responseData)
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {//请求失败处理函数
                console.log("请求失败");
            }
        });
    }
    function onserch() {
        if ($("#txtUserCode").val() == "") {
            alert("请输入会员编号");
        } else {
            BindTree(0, $("#txtUserCode").val(), z)
        }
    }
    function Myonserch() {
        z = 1;
        BindTree(id, $("#txtUserCode").val(), 1)
    }
    function Uponserch() {
        z = z - 1;
        BindTree(id, $("#txtUserCode").val(), z)
    }
    function Downonserch() {
        z = z + 1;
        BindTree(id, $("#txtUserCode").val(), z)
    }
</script>

Chat.FrontWeb/Views/Team/PersonalInfo.cshtml
@model SDMS.DTO.DTO.UserDTO

@{
    ViewBag.Title = "PersonalInfo";
    Layout = "~/Views/Share/_Layout2.cshtml";
}

<h2>个人资料</h2>
<div class="wrapper">
    <section class="panel">
        <!--主体开始-->

        <section>
            <div class="row">
                <div class="col-md-6 tablet-column-reset" style="padding: 10px 40px;">
                    @using (Html.BeginForm("ModifitLoginInfo", "Team", FormMethod.Post))
                    {@Html.HiddenFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">资料详情</h3>
                        </div>
                        <div class="form-horizontal margin-none" id="loginForm">
                            <input type="hidden" name="id" value="1859" runat="server" />
                            <div class="widget-body" style="padding: 20px; overflow: auto;">
                                <div class="form-group">
                                    <label class="col-md-4 control-label">会员编号 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.UserCode, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" }, @value = @Model.UserCode })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">手机号码 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.PhoneNum, new { htmlAttributes = new { @class = "form-control" }, @value = @Model.PhoneNum })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">注册金额 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.RegMoney, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" }, @value = @Model.RegMoney })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">会员级别 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.LevelName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @type = "text" }, @value = @Model.LevelID })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">推荐人编号 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.RecommendCode, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" }, @value = @Model.RecommendCode })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">安置会员编号 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.ParentCode, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" }, @value = @Model.ParentCode })
                                    </div>
                                </div>
                                <div style="clear: both;"></div>

                            </div>
                            <footer class="data-footer innerAll half text-right clearfix">
                                <input type="submit" value="修改" class="btn btn-primary coinkg" />

                            </footer>
                        </div>
                    </div>
                }
                    <div class="panel panel-default" style="margin-top: 20px;">
                        <div class="panel-heading">
                            <h3 class="panel-title">修改登录密码</h3>
                        </div>
                        @using (Html.BeginForm("ModifitLoginPwd", "Team", FormMethod.Post))
                        {@Html.HiddenFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })

                        <div class="form-horizontal margin-none" id="myform">
                            <div class="widget-body" style="padding: 20px; overflow: auto;">
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="firstname">旧登录密码 :</label>
                                    <div class="col-md-8">
                                        <div class="controls">
                                            <input type="password" id="oldpwd" name="oldpwd" class="form-control" autocomplete = "off"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="firstname">新登录密码 :</label>
                                    <div class="col-md-8">
                                        <div class="controls">
                                            @Html.EditorFor(p => p.Password, new { htmlAttributes = new { @class = "form-control", @type = "password", @autocomplete = "off" } })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">确认登录新密码 :</label>
                                    <div class="col-md-8">
                                        <input type="password" id="repwd" name="repwd" class="form-control" autocomplete = "off"/>

                                    </div>
                                </div>

                            </div>
                            <footer class="data-footer innerAll half text-right clearfix">
                                <input type="submit" value="修改" class="btn btn-primary coinkg" />
                            </footer>
                        </div>
                    }
                    </div>
                </div>
                <div class="col-md-6 tablet-column-reset" style="padding: 10px 40px;">
                    @using (Html.BeginForm("ModifitBaseInfo", "Team", FormMethod.Post))
                    {@Html.HiddenFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">个人资料</h3>
                        </div>
                        <div class="form-horizontal margin-none">
                            <div class="widget-body" style="padding: 20px; overflow: auto;">
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="firstname">会员姓名 :</label>
                                    <div class="col-md-8">
                                        <div class="controls">
                                            @Html.EditorFor(p => p.TrueName, new { htmlAttributes = new { @class = "form-control" }, @value = @Model.TrueName })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label">身份证号 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.IdenCode, new { htmlAttributes = new { @class = "form-control" }, @value = @Model.IdenCode })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label">开户银行 :</label>
                                    <div class="col-md-4">
                                        @Html.DropDownList("BankName", new SelectList(ViewBag.BankModelList, "BankName", "BankName", "--请选择--"), new { htmlAttributes = new { @class = "form-control" } })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">银行支行 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.BankBranch, new { htmlAttributes = new { @class = "form-control" }, @value = @Model.BankBranch })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">银行账户 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.BankAccount, new { htmlAttributes = new { @class = "form-control" }, @value = @Model.BankAccount })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">开户姓名 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.BankAccountUser, new { htmlAttributes = new { @class = "form-control" }, @value = @Model.BankAccountUser })
                                    </div>
                                </div>
                            </div>
                            <footer class="data-footer innerAll half text-right clearfix">
                                <input type="submit" value="修改" class="btn btn-primary coinkg" />
                            </footer>
                        </div>
                    </div>
                }
                    @using (Html.BeginForm("ModifitSecodePwd", "Team", FormMethod.Post))
                    {@Html.HiddenFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                    <div class="panel panel-default" style="margin-top: 20px;">
                        <div class="panel-heading">
                            <h3 class="panel-title">修改二级密码</h3>
                        </div>
                        <div class="form-horizontal margin-none" id="myform1">
                            <div class="widget-body" style="padding: 20px;">
                                <div class="form-group">
                                    <label class="col-md-4 control-label" for="firstname">旧二级密码 :</label>
                                    <div class="col-md-8">
                                        <div class="controls">
                                            <input type="password" name="oldsepwd" id="oldsepwd" class="form-control" autocomplete = "off"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">新二级密码 :</label>
                                    <div class="col-md-8">
                                        @Html.EditorFor(p => p.SecondPassword, new { htmlAttributes = new { @class = "form-control", @type = "password", @autocomplete = "off" } })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-md-4 control-label">确认二级密码 :</label>
                                    <div class="col-md-8">
                                        <input type="password" name="resepwd" id="resepwd" class="form-control" autocomplete="off" />
                                    </div>
                                </div>
                            </div>
                            <footer class="data-footer innerAll half text-right clearfix">
                                <input type="submit" value="修改" class="btn btn-primary coinkg" />
                            </footer>
                        </div>
                    </div>
                }
                </div>
            </div>
        </section>

        <!--./主体开始-->
    </section>
</div>

Chat.FrontWeb/Views/Team/RecommendTree.cshtml
@{
    ViewBag.Title = "RecommendTree";
    Layout = "~/Views/Share/_Layout2.cshtml";
}
<link rel="stylesheet" type="text/css" href="/js/themes/default/style.min.css" />
<script type="text/javascript" src="/js/jstree.min.js"></script>
<h2>推荐关系图</h2>
<div class="wrapper">
    <section class="panel">
        <!--主体开始-->
        <section style="padding: 28px;">
            <div class="row">
                会员编号：<input type="text" id="txtUserCode" />
                <input type="button" value="查询" onclick="Serach()" />
                <div class="col-md-12">
                    <!--内容开始-->
                    <div id="tree" class="tree tree-unselectable">
                        <ul id="red">
                            <li data-jstree='{"opened":true}'></li>
                        </ul>
                        <input id="uid" class="userid" type="hidden"/>
                        <input id="tage" class="tage" type="hidden" />
                    </div>
                </div>
            </div>
        </section>
        <!--./主体开始-->
    </section>
</div>
<script>
    $(function () {
        $('#red').jstree({
            'core': {
                'data': {
                    "url": "/Team/TreeMethod?uid=9",
                    "dataType": "json",
                    "data": function (node) {
                        return { "id": node.id };
                    }
                }
            }

        });
        $('#red').jstree().hide_icons();

    })
    function Serach() {
        $('#red').data('jstree', false).empty();
        var usercode = $("#txtUserCode").val();
        console.log(usercode);
        $('#red').jstree({
            'core': {
                'data': {
                    "url": "/Team/TreeSeachMethod?code=" + usercode,
                    "dataType": "json",
                    "data": function (node) {
                        return { "id": node.id };
                    }
                }
            }

        });
        $('#red').jstree().hide_icons();
    }
</script>